apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::972250390970:role/eksctl-eksctl-demo-nodegroup-ng-9-NodeInstanceRole-717RVWN5F0I9
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::972250390970:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-25T18:20:28Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1734"
  uid: 5912af78-6cf9-45e0-99f4-b98cdf4461df
